### PR TITLE
author list was ignoring the rank

### PR DESCRIPTION
**Pull request by mrpatrickwest**
Changed the query to include rank if available and order by that rank

### CODE REVIEW

**Comment by zednis** [comment]
in the test browser on UDCO I saw the following author ordering for

Noble gas isotope abundances in terrestrial fluids
DCO ID: 11121/4317-8058-4791-8747-CC

Authors: Prasolov, Edward; Tolstikhin, Igor; Kikvadze, Olga; Vereina, Olga; Vetrina, Margarite

but the [drupal page](https://deepcarbon.net//dco_dataset_summary?uri=http://info.deepcarbon.net/individual/n6225) has the following author list - which has a different author count and ordering:

Ioffe, A,   http://dx.deepcarbon.net/11121/8576-3222-6850-2026-CC
Kikvadze, Olga, http://dx.deepcarbon.net/11121/2397-9343-7847-5186-CC
Prasolov, Edward,   http://dx.deepcarbon.net/11121/9712-2348-4704-4389-CC
Yakovlev, L,    http://dx.deepcarbon.net/11121/2404-7589-1019-4390-CC
Vereina, Olga,  http://dx.deepcarbon.net/11121/2486-8278-3805-1061-CC
Tolstikhin, Igor,   http://dx.deepcarbon.net/11121/2199-3542-5961-4099-CC
Polyak, Boris,  http://dx.deepcarbon.net/11121/8584-7202-5559-7311-CC
Vetrina, Margarite, http://dx.deepcarbon.net/11121/3174-4746-5341-8386-CC

**Comment by mrpatrickwest** [comment]
The author order on the drupal dataset summary page is also incorrect and needs to be fixed. Separate from this pull request, but will fix as part of the ticket.

**Comment by mrpatrickwest** [comment]
Also need to fix the page to use the query files from deepcarbon instead of tw

**Comment by zednis** [comment]
Author ordering in the browser is also different from the ordering in the drupal summary page for "DCO Research Activities Query Set"  ([drupal summary page](https://deepcarbon.net//dco_dataset_summary?uri=http://info.deepcarbon.net/individual/n3117))

**Comment by olyerickson** [comment]
The Drupal data set summary includes probably the oldest of our queries
against the data set metadata. I know for a fact it doesn't consider rank.

When it was created, we were more concerned that the dog could speak than
what he was saying...

On Wednesday, July 15, 2015, Patrick West notifications@github.com wrote:

> Merged #13 https://github.com/tetherless-world/dco-s2s-browsers/pull/13.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tetherless-world/dco-s2s-browsers/pull/13#event-356994889
> .

## 

John S. Erickson, Ph.D.
Director of Operations, The Rensselaer IDEA
Deputy Director, Web Science Research Center (RPI)
http://tw.rpi.edu olyerickson@gmail.com
Twitter & Skype: olyerickson

**Pull request merged**
