### PR TITLE
Checking to see if result element has any actual content

### PR DESCRIPTION
**Pull request by mrpatrickwest**

### CODE REVIEW

**Comment by zednis** [comment]
It looks good to me.  Let's put it in test.

**Comment by zednis** [comment]
I updated UDCO with this change and attempted to test it by putting "foo" in the "Search People by Name" facet.

I see the following:

screen shot 2015-04-30 at 7 57 36 pm
1. Is this invoking the code from this pull request?
2. Do we want this to show **"1-NaN of NaN"** in the result count?

**Comment by mrpatrickwest** [comment]
Actually shouldn't see NaN. But no matter what I tried I couldn't get it to display 0. is_nan didn't work. isnull, isset, etc... I created a separate ticket for the NaN problem in Jira. Frank's issue was that it should what looked like one result.

**Comment by mrpatrickwest** [comment]
And yes, this is using the code from this pull request. UDCO is where I implemented it.

**Comment by zednis** [comment]
Perhaps an update to getSearchResultCount( ) is needed to resolve the count issue?  If that is another issue we can mess around with it in that context.  If the current behavior on UDCO is acceptable then you have my :+1:  to approve and close the pull request.

**Comment by zednis** [comment]
Oh, additional question.  Where did you implement this on UDCO?  I added it to /var/www/browsers/opensearch/services/people/people.php last night after you opened the pull request because it was not already there.  Did you update another copy of people.php on UDCO as well?

... we really need to get the install normalized...

**Comment by zednis** [comment]
we moved this fix for 1-NaN into the config.php file from the s2s repository, correct?  

If so, should we merge this fix as well or drop it since we implemented a fix 'upstream'?

**Comment by mrpatrickwest** [comment]
Yes, the fix for this is up in the s2s repository for opensearch/config.php (or utils.php, can't remember) and in the widget ResultsListWidget.js. So we can close this pull request if you'd like

**Comment by mrpatrickwest** [comment]
The file changed in this pull request doesn't need to be changed. With the change happening "up stream"  the change is no longer needed.

**Pull request closed without merging**
